// =============================================================================
// EEE4120F Practical 4 — StarCore-1 Processor
// File        : GPR_tb.v
// Description : Testbench for the General Purpose Register File (GPR).
//
// HOW THIS TESTBENCH WORKS
// ------------------------
// Unlike the ALU, the GPR has a CLOCK because writes are synchronous —
// they only commit on the rising edge of clk. Reads are asynchronous
// (combinational), so read data appears immediately when the address changes.
//
// The clock is generated by:
//   initial clk = 0;
//   always #5 clk = ~clk;     <- toggles every 5ns -> 10ns period = 100 MHz
//
// KEY CONCEPT: write-before-read vs read-before-write
// ---------------------------------------------------
// Because reads are ASYNC and writes are SYNC:
//   - If you read the same register you're about to write, you get the
//     OLD value (before the clock edge).
//   - After the posedge, the new value appears immediately on the read port.
// This is intentional for a single-cycle processor — the control unit
// cannot accidentally read a value that hasn't been committed yet.
//
// Group 4 (write-before-read) demonstrates and verifies this behavior,
// which is important to describe in your report.
//
// Run from tb/:
//   iverilog -Wall -I ../src -o ../build/gpr_sim ../src/GPR.v GPR_tb.v
//   ../build/gpr_sim
//   gtkwave ../waves/gpr_tb.vcd &
// =============================================================================

`timescale 1ns / 1ps
`include "../src/Parameter.v"

module GPR_tb;

    reg        clk;
    reg        reg_write_en;
    reg  [2:0] reg_write_dest;
    reg  [15:0] reg_write_data;
    reg  [2:0] reg_read_addr_1;
    reg  [2:0] reg_read_addr_2;
    wire [15:0] reg_read_data_1;
    wire [15:0] reg_read_data_2;

    GPR uut (
        .clk              (clk),
        .reg_write_en     (reg_write_en),
        .reg_write_dest   (reg_write_dest),
        .reg_write_data   (reg_write_data),
        .reg_read_addr_1  (reg_read_addr_1),
        .reg_read_data_1  (reg_read_data_1),
        .reg_read_addr_2  (reg_read_addr_2),
        .reg_read_data_2  (reg_read_data_2)
    );

    // 10 ns clock period (100 MHz)
    initial clk = 1'b0;
    always  #5 clk = ~clk;

    initial begin
        $dumpfile("../waves/gpr_tb.vcd");
        $dumpvars(0, GPR_tb);
    end

    integer fail_count;
    integer test_id;
    integer i;

    initial begin
        fail_count = 0;
        test_id    = 1;
    end

    task check16;
        input [15:0] got;
        input [15:0] expected;
        input [63:0] id;
        begin
            if (got !== expected) begin
                $display("FAIL [T%0d]: got = 0x%h, expected = 0x%h", id, got, expected);
                fail_count = fail_count + 1;
            end else
                $display("PASS [T%0d]: value = 0x%h", id, got);
        end
    endtask

    initial begin
        $display("=== GPR Testbench ===");

        // Initialise all inputs to safe inactive state
        reg_write_en    = 1'b0;
        reg_write_dest  = 3'd0;
        reg_write_data  = 16'd0;
        reg_read_addr_1 = 3'd0;
        reg_read_addr_2 = 3'd0;

        // Wait one full clock cycle so the GPR's initial block completes
        @(posedge clk); #1;

        // =================================================================
        // GROUP 1: Write a unique value to every register then read it back
        // =================================================================
        // Sequence for each register:
        //   1. Assert reg_write_en, set address and data
        //   2. Wait for posedge clk — write commits here (non-blocking <=)
        //   3. De-assert write enable
        //   4. Set read address, wait #2 for combinational path to settle
        //   5. Compare read data against expected
        // =================================================================
        $display("--- Group 1: Write and read back all 8 registers ---");

        reg_write_en = 1'b1; reg_write_dest = 3'd0; reg_write_data = 16'hA000;
        @(posedge clk); #1; reg_write_en = 1'b0;
        reg_read_addr_1 = 3'd0; #2;
        check16(reg_read_data_1, 16'hA000, test_id); test_id = test_id + 1;

        reg_write_en = 1'b1; reg_write_dest = 3'd1; reg_write_data = 16'hB001;
        @(posedge clk); #1; reg_write_en = 1'b0;
        reg_read_addr_1 = 3'd1; #2;
        check16(reg_read_data_1, 16'hB001, test_id); test_id = test_id + 1;

        reg_write_en = 1'b1; reg_write_dest = 3'd2; reg_write_data = 16'hC002;
        @(posedge clk); #1; reg_write_en = 1'b0;
        reg_read_addr_1 = 3'd2; #2;
        check16(reg_read_data_1, 16'hC002, test_id); test_id = test_id + 1;

        reg_write_en = 1'b1; reg_write_dest = 3'd3; reg_write_data = 16'hD003;
        @(posedge clk); #1; reg_write_en = 1'b0;
        reg_read_addr_1 = 3'd3; #2;
        check16(reg_read_data_1, 16'hD003, test_id); test_id = test_id + 1;

        reg_write_en = 1'b1; reg_write_dest = 3'd4; reg_write_data = 16'hE004;
        @(posedge clk); #1; reg_write_en = 1'b0;
        reg_read_addr_1 = 3'd4; #2;
        check16(reg_read_data_1, 16'hE004, test_id); test_id = test_id + 1;

        reg_write_en = 1'b1; reg_write_dest = 3'd5; reg_write_data = 16'hF005;
        @(posedge clk); #1; reg_write_en = 1'b0;
        reg_read_addr_1 = 3'd5; #2;
        check16(reg_read_data_1, 16'hF005, test_id); test_id = test_id + 1;

        reg_write_en = 1'b1; reg_write_dest = 3'd6; reg_write_data = 16'h1006;
        @(posedge clk); #1; reg_write_en = 1'b0;
        reg_read_addr_1 = 3'd6; #2;
        check16(reg_read_data_1, 16'h1006, test_id); test_id = test_id + 1;

        reg_write_en = 1'b1; reg_write_dest = 3'd7; reg_write_data = 16'h2007;
        @(posedge clk); #1; reg_write_en = 1'b0;
        reg_read_addr_1 = 3'd7; #2;
        check16(reg_read_data_1, 16'h2007, test_id); test_id = test_id + 1;

        // =================================================================
        // GROUP 2: Disabled write must NOT change the register
        // =================================================================
        // reg_write_en = 0 -> the always @(posedge clk) block's 'if' is
        // false, so no write occurs even though the clock edge happens.
        // R0 must still hold 0xA000 from Group 1.
        // =================================================================
        $display("--- Group 2: Disabled write must not modify register ---");

        reg_write_en = 1'b0; reg_write_dest = 3'd0; reg_write_data = 16'hDEAD;
        @(posedge clk); #1;               // clock ticks but write is gated off
        reg_read_addr_1 = 3'd0; #2;
        check16(reg_read_data_1, 16'hA000, test_id); test_id = test_id + 1;

        // =================================================================
        // GROUP 3: Simultaneous read from BOTH ports
        // =================================================================
        // The GPR has two independent read ports. Both can be active at the
        // same time — this is what allows R-type instructions to read RS1
        // and RS2 in the same cycle.
        // Port 1 reads reg_read_addr_1; Port 2 reads reg_read_addr_2.
        // Both outputs update combinationally with no clock needed.
        // =================================================================
        $display("--- Group 3: Simultaneous dual-port read ---");

        reg_read_addr_1 = 3'd1; reg_read_addr_2 = 3'd3; #2;
        check16(reg_read_data_1, 16'hB001, test_id); test_id = test_id + 1;
        check16(reg_read_data_2, 16'hD003, test_id); test_id = test_id + 1;

        // Try another pair to confirm ports are truly independent
        reg_read_addr_1 = 3'd5; reg_read_addr_2 = 3'd7; #2;
        check16(reg_read_data_1, 16'hF005, test_id); test_id = test_id + 1;
        check16(reg_read_data_2, 16'h2007, test_id); test_id = test_id + 1;

        // =================================================================
        // GROUP 4: Read-during-write (write-before-read behaviour)
        // =================================================================
        // Key insight: reads are COMBINATIONAL (immediate), writes are
        // SYNCHRONOUS (committed at posedge clk).
        //
        // If we set reg_read_addr_1 == reg_write_dest while write is
        // pending, the read port sees the OLD value stored in the register
        // array — because the new value hasn't been committed yet.
        //
        // After posedge clk, the write commits and the read port
        // immediately reflects the new value (no extra clock needed,
        // because the read is combinational).
        //
        // This is the expected and CORRECT behaviour for single-cycle RISC.
        // It means an instruction can't accidentally read its own result
        // within the same cycle it writes it.
        // =================================================================
        $display("--- Group 4: Read address == write address during write ---");

        reg_write_en    = 1'b1;
        reg_write_dest  = 3'd2;
        reg_write_data  = 16'hBEEF;
        reg_read_addr_1 = 3'd2;   // same register — will we see old or new?
        #2;                        // wait BEFORE the clock edge

        // Before posedge: read port sees OLD value (0xC002 from Group 1)
        $display("INFO [T%0d]: Before posedge — read = 0x%h (old value, should be 0xC002)",
                 test_id, reg_read_data_1);
        check16(reg_read_data_1, 16'hC002, test_id); test_id = test_id + 1;

        @(posedge clk); #1;        // write commits here
        reg_write_en = 1'b0;
        #2;

        // After posedge: read port now sees NEW value (0xBEEF)
        check16(reg_read_data_1, 16'hBEEF, test_id); test_id = test_id + 1;

        $display("");
        if (fail_count == 0)
            $display("=== ALL %0d TESTS PASSED ===", test_id - 1);
        else
            $display("=== %0d / %0d TESTS FAILED ===", fail_count, test_id - 1);

        $finish;
    end

endmodule